# Generated by Django 5.1.2 on 2024-11-04 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment_income', 'Investment Income'), ('gift', 'Gift'), ('savings', 'Savings'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('debt_repayment', 'Debt Repayment'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('charity', 'Charity'), ('taxes', 'Taxes'), ('subscriptions', 'Subscriptions'), ('miscellaneous', 'Miscellaneous')])),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_api.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_api.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_color', models.CharField(choices=[('#4CAF50', 'Green'), ('#F44336', 'Red'), ('#FFC107', 'Amber'), ('#2196F3', 'Blue'), ('#FF9800', 'Orange'), ('#9C27B0', 'Purple'), ('#3F51B5', 'Indigo'), ('#009688', 'Teal'), ('#8BC34A', 'Light Green'), ('#795548', 'Brown'), ('#607D8B', 'Blue Grey'), ('#E91E63', 'Pink'), ('#00BCD4', 'Cyan'), ('#673AB7', 'Deep Purple'), ('#F57C00', 'Dark Orange')], default='#4CAF50', max_length=7)),
                ('base_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_api.basecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'base_category', 'custom_name')},
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default='null_category', on_delete=django.db.models.deletion.SET_DEFAULT, to='finance_api.usercategory'),
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('base_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_api.basecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_api.usercategory')),
            ],
            options={
                'unique_together': {('user', 'base_category', 'user_category', 'start_date', 'end_date')},
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
