# Generated by Django 5.1.2 on 2024-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0002_basecategory_alter_account_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(fields=('user', 'base_category', 'custom_name'), name='unique category for user'),
        ),
    ]
