# Generated by Django 5.1.2 on 2024-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0003_alter_usercategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercategory',
            name='unique category for user',
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(fields=('user_id', 'base_category_id', 'custom_name'), name='unique category for user'),
        ),
    ]
