# Generated by Django 5.1.2 on 2024-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_remove_usercategory_unique_category_for_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercategory',
            name='unique category for user',
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_name__isnull', True)), fields=('user_id', 'base_category_id', 'custom_name'), name='unique category for user'),
        ),
    ]
