# Generated by Django 5.1.2 on 2024-11-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0007_remove_usercategory_unique_category_for_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='base_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_api.basecategory'),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_api.usercategory'),
        ),
    ]
