# Generated by Django 5.1.2 on 2024-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0008_alter_categorybudget_base_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='display_color',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='display_color',
        ),
    ]
