# Generated by Django 5.1.3 on 2024-11-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecategory',
            options={'verbose_name_plural': 'base categories'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'user categories'},
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="account's money amount"),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BYN', 'Belarusian Rouble')], default='BYN', max_length=3, verbose_name='currency of the account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name="account's name"),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name="account's holder"),
        ),
    ]
