# Generated by Django 5.1.3 on 2024-11-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0011_alter_basecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_api.account', verbose_name="transaction's account"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount of the transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default='null_category', on_delete=django.db.models.deletion.SET_DEFAULT, to='finance_api.usercategory', verbose_name='transaction category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date on which transaction was made'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='description of the transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer')], default='EX', max_length=2, verbose_name='the type of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL, verbose_name="transaction's user"),
        ),
    ]
