services:
  # Django main API service
  django_finance:
    build: ./finance_project
    hostname: "finance_project"
    restart: on-failure
    ports:
      - "5000:8000"
    volumes:
      - ./finance_project/finance_app:/app
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_PROD_URL=${REDIS_PROD_URL}
      - REDIS_TEST_URL=${REDIS_TEST_URL}
      - DJANGO_SECRET=${DJANGO_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis

  # FASTAPI budjet reports API service
  fastapi_reports:
    build: ./finance_reports
    hostname: "finance_reports"
    restart: on-failure
    ports:
      - "5001:8080"
    volumes:
      - ./finance_reports:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # postgersql db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10

  # cache, celery brocker
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:


